gpp -n +c "//" "\n" -I Common Control\Control.vhd 						> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\Control.vhd
gpp -n +c "//" "\n" -I Common Control\Stack.vhd 						> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\Stack.vhd
gpp -n +c "//" "\n" -I Common ALU\ALU.vhd 								> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\ALU.vhd
gpp -n +c "//" "\n" -I Common Master\Master.vhd 						> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\Master.vhd
gpp -n +c "//" "\n" -I Common Memory\MemoryController.vhd 				> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\MemoryController.vhd
gpp -n +c "//" "\n" -I Common Memory\Memory.vhd 						> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\Memory.vhd
gpp -n +c "//" "\n" -I Common Memory\RegistryInternal.vhd 				> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\RegistryInternal.vhd
gpp -n +c "//" "\n" -I Common Peripherals\ButtonDriver\btndriver.vhd 	> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\btndriver.vhd
gpp -n +c "//" "\n" -I Common Peripherals\SevensegDriver\b2bcd.vhd 		> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\b2bcd.vhd
gpp -n +c "//" "\n" -I Common Peripherals\SevensegDriver\ssgddriver.vhd > C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\ssgddriver.vhd
gpp -n +c "//" "\n" -I Common Peripherals\Interrupt.vhd	 				> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\Interrupt.vhd
gpp -n +c "//" "\n" -I Common Peripherals\I2S\I2SDriverIn.vhd 			> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\I2SDriverIn.vhd
gpp -n +c "//" "\n" -I Common Peripherals\I2S\I2SDriverOut.vhd 			> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\I2SDriverOut.vhd
gpp -n +c "//" "\n" -I Common Peripherals\I2S\I2SMonoIn.vhd 			> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\I2SMonoIn.vhd
gpp -n +c "//" "\n" -I Common Peripherals\I2S\I2SMonoOut.vhd 			> C:\Users\magnu\Documents\AAU\4_Semester\QUARTUS_PROJECTS\CPU_V1_CPP\Project_files\I2SMonoOut.vhd