gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\ALU\ALU.vhd 								> VHDL_RAW\ALU.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Control\Control.vhd 						> VHDL_RAW\Control.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Control\Stack.vhd 							> VHDL_RAW\Stack.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Control\MemoryController.vhd 				> VHDL_RAW\MemoryController.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Fir_Filter\Filter.vhd 						> VHDL_RAW\Filter.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Master\Master.vhd 							> VHDL_RAW\Master.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Memory\Memory.vhd 							> VHDL_RAW\Memory.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Memory\RegistryInternal.vhd 				> VHDL_RAW\RegistryInternal.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\ButtonDriver\btndriver.vhd 	> VHDL_RAW\btndriver.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\SevensegDriver\b2bcd.vhd 		> VHDL_RAW\b2bcd.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\SevensegDriver\ssgddriver.vhd 	> VHDL_RAW\ssgddriver.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\Interrupt.vhd	 				> VHDL_RAW\Interrupt.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\I2S\I2SDriverIn.vhd 			> VHDL_RAW\I2SDriverIn.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\I2S\I2SDriverOut.vhd 			> VHDL_RAW\I2SDriverOut.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\I2S\I2SMonoIn.vhd 				> VHDL_RAW\I2SMonoIn.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Peripherals\I2S\I2SMonoOut.vhd 			> VHDL_RAW\I2SMonoOut.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Test_Benches\CPU_V1_TB.vhd 				> VHDL_RAW\CPU_V1_TB.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Test_Benches\FIR_TB.vhd 					> VHDL_RAW\FIR_TB.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Simulation_Files\custom_wave.do 			> VHDL_RAW\custom_wave.do
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\Simulation_Files\wave.do 					> VHDL_RAW\wave.do
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\IP_Cores\MemAuto.vhd 						> VHDL_RAW\MemAuto.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\IP_Cores\PLL.vhd 							> VHDL_RAW\PLL.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\IP_Cores\Multiplier_1.vhd 					> VHDL_RAW\Multiplier_1.vhd
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\IP_Cores\MemAuto.qip 						> VHDL_RAW\MemAuto.qip
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\IP_Cores\PLL.qip 							> VHDL_RAW\PLL.qip
gpp -n +c "//" "\n" -I VHDL_GPP\Headers VHDL_GPP\IP_Cores\Multiplier_1.qip 					> VHDL_RAW\Multiplier_1.qip